#!/bin/sh
echo Content-type: text/html
echo
echo
SHOWDATE=`date +"%B %d, %Y %I:%M:%S %p"`
WIFI=`awk '{if(NR == 1){print $4}}' /tmp/dhcp.leases`
#WIFI1=`awk '{if(NR == 2){print $4}}' /tmp/dhcp.leases`
#WIFI2=`awk '{if(NR == 3){print $4}}' /tmp/dhcp.leases`
#WIFI3=`awk '{if(NR == 4){print $4}}' /tmp/dhcp.leases`
#WIFI4=`awk '{if(NR == 5){print $4}}' /tmp/dhcp.leases`


echo "<br />"

echo " <font size="2"> device connected </font>"
echo "<br />"
echo "<font size="2"  > $WIFI   </font> "
echo "<br />"
echo " <font size="2" >$WIFI1  </font> "
echo "<br />"
echo " <font size="2" >$WIFI2   </font> <br />"
echo "<br />"
echo " <font size="2" >$WIFI3   </font> "
echo "<br/>"
echo " <font size="2" >$WIFI4    </font>"
echo "<br/>"
